# Build the claude.ai Artifact version of the Post-Unicorn Finance Atlas.
# Reads data/evidence/atlas.csv -> writes scratchpad/atlas_artifact.html
# (content-only fragment: no doctype/html/head/body per Artifact rules).
import csv, html, json, os, re
from collections import Counter, OrderedDict, defaultdict

REPO = r'C:\Users\cobys\projects\post-unicorn-finance'
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'atlas_artifact.html')
WRAP_OUT = r'C:\Users\cobys\Downloads\atlas-site\index.html'
FEEDBACK_EMAIL = 'cstillman@umass.edu'
DATE = '2026-07-07'

# world map path data (generated by gen_world_map_paths.py from Natural Earth 110m, public domain)
with open(os.path.join(REPO, 'scripts', 'world_map_paths.json'), encoding='utf-8') as f:
    MAP_DATA = json.load(f)
ATLAS_TO_NE = {'United States': 'United States of America'}  # every other atlas name matches NE ADMIN

with open(os.path.join(REPO, 'data', 'evidence', 'atlas.csv'), encoding='utf-8-sig') as f:
    rows = list(csv.DictReader(f))

CLASS_ORDER = OrderedDict([
    ('Nimble',              ('Nimble', '#2e7d32', 'Smaller markets engineered for fast liquidity — exits under 6 years by design.')),
    ('SMV',                 ('Strategic Middle Ventures', '#b7791f', 'Large-ish markets aiming for sub-unicorn outcomes ($50–500M) on a similar-or-better clock (~7–9y).')),
    ('Permanent',           ('Permanent Capital', '#37568c', 'No forced exit. Evergreen funds, steward-ownership, holdcos and family offices that compound for decades.')),
    ('Studio',              ('Venture Studios', '#5b4a8a', 'Build and own their own products — company creation is the investment activity.')),
    ('Impact Capital',      ('Impact Capital', '#8a4664', 'Mission- and impact-driven allocators with an explicit anti-power-law thesis.')),
    ('Reserved',            ('Trends / Watch', '#5c6660', 'Classes being watched — Operator (search funds / ETA) and Sovereign — no verified funds yet.')),
    ('Under Review',        ('Under Review', '#77705f', 'Borderline entries — revenue-based lenders, micro-PE and secondaries whose “return” mechanics are still being ruled on.')),
    ('Excluded-Traditional',('Excluded — Traditional', '#494f4c', 'Classic unicorn-chasing VC, kept only as the contrast baseline.')),
])
ACTIVE = {'Nimble', 'SMV', 'Permanent', 'Studio', 'Impact Capital'}

def esc(s): return html.escape((s or '').strip())

def link(u):
    u = (u or '').strip()
    if u and not u.startswith('http'): u = 'https://' + u
    return u

counts = Counter(r['asset_class'] for r in rows)
countries = Counter(r['country'] for r in rows if r.get('country') and r['country'] != 'Unknown')
horizoned = sum(1 for r in rows if (r.get('horizon_years') or '').strip())

order_key = {k: i for i, k in enumerate(CLASS_ORDER)}
rows.sort(key=lambda r: (order_key.get(r['asset_class'], 99), (r['name'] or '').lower()))

# ---------- entity rows ----------
def row_html(r):
    cls = r['asset_class']
    label, color, _ = CLASS_ORDER.get(cls, (cls, '#666', ''))
    hz = (r.get('horizon_years') or '').strip()
    hz_disp = (hz + 'y') if hz and hz.lower() not in ('decades', 'permanent') else (hz or '—')
    country = esc(r.get('country') or 'Unknown')
    signal = esc(r.get('evidence_signal') or '')
    quote = esc(r.get('exit_quote') or '')
    ev_url = link(r.get('liquidity_evidence_url') or '')
    site = link(r.get('website'))
    flag = esc(r.get('audit_flag') or '')
    tier = esc(r.get('tier') or '')
    alloc = (r.get('allocator') or '').strip().lower()
    search = ' '.join([r['name'], cls, country, r.get('evidence_signal') or '']).lower()
    body = ['<div class="r-body">']
    if signal:
        body.append('<p class="r-signal">%s</p>' % signal)
    if quote:
        cite = (' <a href="%s" target="_blank" rel="noopener">source ↗</a>' % ev_url) if ev_url else ''
        body.append('<blockquote class="r-quote">“%s”%s</blockquote>' % (quote, cite))
    meta = []
    if tier: meta.append('<span class="chip">%s</span>' % tier)
    if alloc == 'no': meta.append('<span class="chip chip-warn">allocator: under question</span>')
    if flag: meta.append('<span class="chip chip-flag" title="%s">flagged for review</span>' % flag)
    if meta: body.append('<p class="r-meta">%s</p>' % ' '.join(meta))
    acts = []
    if site: acts.append('<a class="r-act" href="%s" target="_blank" rel="noopener">Visit site ↗</a>' % esc(site))
    acts.append('<a class="r-act" href="#feedback" data-entity="%s" onclick="atlasPrefill(this)">Suggest a correction ✎</a>' % esc(r['name']))
    body.append('<p class="r-actions">%s</p>' % ' · '.join(acts))
    body.append('</div>')
    return (
        '<details class="row" data-class="%s" data-country="%s" data-search="%s">'
        '<summary><span class="r-name">%s</span>'
        '<span class="pill" style="--pc:%s">%s</span>'
        '<span class="r-hz">%s</span>'
        '<span class="r-country">%s</span></summary>%s</details>'
    ) % (esc(cls), country, esc(search), esc(r['name']), color, esc(cls), esc(hz_disp), country, ''.join(body))

rows_html = '\n'.join(row_html(r) for r in rows)

# ---------- stack cards ----------
cards = []
for key, (label, color, blurb) in CLASS_ORDER.items():
    n = counts.get(key, 0)
    kind = 'active' if key in ACTIVE else 'meta'
    cards.append(
        '<button class="card %s" data-filter="%s" style="--pc:%s">'
        '<span class="c-head"><span class="c-title">%s</span><span class="c-n">%d</span></span>'
        '<span class="c-blurb">%s</span></button>' % (kind, esc(key), color, esc(label), n, esc(blurb)))
cards_html = '\n'.join(cards)

chips_html = '<button class="fchip active" data-filter="*">All <b>%d</b></button>' % len(rows) + ''.join(
    '<button class="fchip" data-filter="%s" style="--pc:%s">%s <b>%d</b></button>'
    % (esc(k), v[1], esc(k), counts.get(k, 0)) for k, v in CLASS_ORDER.items() if counts.get(k, 0))

suggest_mail = ('mailto:%s?subject=%s&body=%s' % (
    FEEDBACK_EMAIL, html.escape('Atlas suggestion: new fund'),
    html.escape('Fund name:%0AWebsite:%0AWhy it belongs (their own words, with a link):%0AStated exit horizon, if any:%0A')))

# ================= charts (hand-built SVG) =================
MONO = 'ui-monospace,Consolas,monospace'
INK, MUTED = '#141d1b', '#5c6660'

def svg_open(w, h, label):
    return ('<svg viewBox="0 0 %d %d" role="img" aria-label="%s" '
            'style="width:100%%;height:auto;max-width:%dpx;display:block">' % (w, h, esc(label), w))

def txt(x, y, s, size=11, fill=MUTED, anchor='start', weight='400', fam=MONO):
    return ('<text x="%g" y="%g" font-family="%s" font-size="%g" fill="%s" '
            'text-anchor="%s" font-weight="%s">%s</text>' % (x, y, fam, size, fill, anchor, weight, esc(str(s))))

# ---- chart 1: funds by class (horizontal bars) ----
def chart_classes():
    items = [(k, counts.get(k, 0)) for k in CLASS_ORDER if counts.get(k, 0)]
    max_n = max(n for _, n in items)
    row_h, label_w, bar_w = 27, 150, 380
    w, h = 640, len(items) * row_h + 16
    out = [svg_open(w, h, 'Number of funds in each asset class')]
    for i, (k, n) in enumerate(items):
        y = i * row_h + 12
        color = CLASS_ORDER[k][1]
        bw = max(3, n / max_n * bar_w)
        pct = 100.0 * n / len(rows)
        out.append(txt(label_w - 8, y + 12, k, anchor='end', fill=INK, fam='system-ui,sans-serif'))
        out.append('<rect x="%d" y="%g" width="%g" height="16" rx="2" fill="%s"><title>%s: %d funds (%.0f%%)</title></rect>'
                   % (label_w, y, bw, color, esc(k), n, pct))
        out.append(txt(label_w + bw + 8, y + 12, '%d · %.0f%%' % (n, pct), fill=MUTED))
    out.append('</svg>')
    return ''.join(out)

# ---- chart 2: liquidity horizons (vertical bars on a time axis) ----
def horizon_bucket(r):
    s = (r.get('horizon_years') or '').strip().lower()
    if s in ('decades', 'permanent', 'forever'):
        return 'No exit'
    nums = [float(x) for x in re.findall(r'\d+\.?\d*', s)]
    if nums:
        m = sum(nums) / len(nums)
        if m <= 2: return '≤2y'
        if m <= 3: return '2–3y'
        if m <= 5: return '3–5y'
        if m < 6: return '5–6y'
        if m <= 9.5: return '6–9y'
        return '10y+'
    if r['asset_class'] == 'Permanent' or (r.get('liquidity_band') or '') == 'Permanent':
        return 'No exit'
    return 'Not stated'

H_BUCKETS = ['≤2y', '2–3y', '3–5y', '5–6y', '6–9y', '10y+', 'No exit', 'Not stated']
H_COLORS = {'≤2y': '#1b5e20', '2–3y': '#2e7d32', '3–5y': '#43932f', '5–6y': '#6aa84f',
            '6–9y': '#b7791f', '10y+': '#8a5a1a', 'No exit': '#37568c', 'Not stated': '#9aa39d'}

def chart_horizons():
    bc = Counter(horizon_bucket(r) for r in rows)
    max_n = max(bc.get(b, 0) for b in H_BUCKETS)
    w, h, plot_h, base = 640, 235, 160, 190
    slot = w / len(H_BUCKETS)
    out = [svg_open(w, h, 'Distribution of stated liquidity horizons')]
    out.append('<line x1="0" y1="%d" x2="%d" y2="%d" stroke="#dde2da" stroke-width="1"/>' % (base, w, base))
    for i, b in enumerate(H_BUCKETS):
        n = bc.get(b, 0)
        x = i * slot + slot / 2
        bh = max(3, n / max_n * plot_h) if n else 0
        if n:
            out.append('<rect x="%g" y="%g" width="44" height="%g" rx="2" fill="%s"><title>%s: %d funds</title></rect>'
                       % (x - 22, base - bh, bh, H_COLORS[b], esc(b), n))
            out.append(txt(x, base - bh - 7, n, size=12.5, fill=INK, anchor='middle', weight='600'))
        out.append(txt(x, base + 17, b, anchor='middle'))
    out.append(txt(0, h - 3, 'faster capital return → longer hold', size=10.5))
    out.append('</svg>')
    return ''.join(out)

# ---- chart 3: countries x class (stacked horizontal bars) ----
def chart_countries():
    by_country = defaultdict(Counter)
    for r in rows:
        c = (r.get('country') or 'Unknown').strip() or 'Unknown'
        by_country[c][r['asset_class']] += 1
    ordered = sorted(by_country.items(), key=lambda kv: (-sum(kv[1].values()), kv[0]))
    row_h, label_w, bar_w = 23, 158, 400
    max_n = sum(ordered[0][1].values())
    w, h = 660, len(ordered) * row_h + 10
    out = [svg_open(w, h, 'Number of funds per country, split by asset class')]
    for i, (c, cc) in enumerate(ordered):
        y = i * row_h + 6
        total = sum(cc.values())
        label = c if c != 'Unknown' else 'Not stated / remote'
        out.append(txt(label_w - 8, y + 11, label, anchor='end', fill=INK, fam='system-ui,sans-serif'))
        x = float(label_w)
        for k in CLASS_ORDER:
            n = cc.get(k, 0)
            if not n: continue
            seg = max(2.0, n / max_n * bar_w)
            out.append('<rect x="%g" y="%g" width="%g" height="14" fill="%s"><title>%s — %s: %d</title></rect>'
                       % (x, y, seg - 1, CLASS_ORDER[k][1], esc(label), esc(k), n))
            x += seg
        out.append(txt(x + 7, y + 11, total, fill=MUTED))
    out.append('</svg>')
    return ''.join(out), len(ordered)

legend_chips = ''.join('<span class="lg" style="--pc:%s"><i></i>%s</span>' % (v[1], esc(k))
                       for k, v in CLASS_ORDER.items() if counts.get(k, 0))
country_chart_svg, n_country_bars = chart_countries()

# ---- chart 4: world choropleth (self-contained inline SVG, click-to-filter) ----
# Country polygons are embedded at build time from Natural Earth 110m (public domain);
# the browser fetches nothing. Shade = fund count; click a shaded country to filter the catalog.
NE_OF_ATLAS = {'United States': 'United States of America'}  # every other atlas name matches NE ADMIN
ATLAS_OF_NE = {v: k for k, v in NE_OF_ATLAS.items()}
MAP_BASE = '#e6eae5'          # countries with no funds
MAP_STROKE = '#cfd6cd'
MAP_BANDS = [(1, '#cfe0dd', '1'), (4, '#9ec6c0', '2–4'), (10, '#66a49a', '5–10'),
             (30, '#2f7d72', '11–30'), (10 ** 9, '#0f5257', '30+')]

def map_fill(n):
    if n <= 0:
        return MAP_BASE
    for hi, col, _ in MAP_BANDS:
        if n <= hi:
            return col
    return MAP_BANDS[-1][1]

def _map_country(ne_name, geo, n):
    atlas = ATLAS_OF_NE.get(ne_name, ne_name)
    fill = map_fill(n)
    common = 'fill="%s" stroke="%s" stroke-width="0.4"' % (fill, MAP_STROKE)
    if n:
        title = '<title>%s — %d fund%s (click to filter)</title>' % (esc(atlas), n, '' if n == 1 else 's')
        attrs = ('class="mc" data-country="%s" tabindex="0" role="button" aria-label="%s, %d funds" %s'
                 % (esc(atlas), esc(atlas), n, common))
    else:
        title, attrs = '', 'class="mc0" %s' % common
    if geo['d']:
        return '<path d="%s" fill-rule="evenodd" %s>%s</path>' % (geo['d'], attrs, title)
    return '<circle cx="%g" cy="%g" r="3.2" %s>%s</circle>' % (geo['cx'], geo['cy'], attrs, title)

def chart_worldmap():
    map_counts = Counter()
    for r in rows:
        c = (r.get('country') or '').strip()
        if c and c != 'Unknown':
            map_counts[c] += 1
    unknown_n = sum(1 for r in rows if (r.get('country') or 'Unknown').strip() in ('', 'Unknown'))
    vb = MAP_DATA['viewBox']
    entries = [(ne, geo, map_counts.get(ATLAS_OF_NE.get(ne, ne), 0))
               for ne, geo in MAP_DATA['countries'].items()]
    # zero-fund countries first (background layer), shaded countries painted on top
    ordered = [e for e in entries if not e[2]] + [e for e in entries if e[2]]
    body = ''.join(_map_country(ne, geo, n) for ne, geo, n in ordered)
    svg = ('<svg viewBox="0 0 %g %g" role="img" aria-label="World map of funds by country" '
           'class="worldmap" xmlns="http://www.w3.org/2000/svg">%s</svg>' % (vb[2], vb[3], body))
    legend = '<span class="mlg"><i style="background:%s;border:1px solid %s"></i>none</span>' % (MAP_BASE, MAP_STROKE)
    legend += ''.join('<span class="mlg"><i style="background:%s"></i>%s</span>' % (col, lab)
                      for _, col, lab in MAP_BANDS)
    return svg, legend, unknown_n, len(map_counts)

world_svg, world_legend, world_unknown_n, world_country_n = chart_worldmap()

CSS = """
:root{
  --paper:#f5f6f2; --ink:#141d1b; --muted:#5c6660; --rule:#dde2da;
  --teal:#0f5257; --teal-deep:#0c2426; --teal-ink:#0a3d41; --amber:#b7791f;
  --serif:'Iowan Old Style','Palatino Linotype',Palatino,Georgia,serif;
  --sans:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;
  --mono:ui-monospace,'SF Mono','Cascadia Mono',Consolas,monospace;
}
*{box-sizing:border-box}
body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans);font-size:15.5px;line-height:1.55}
a{color:var(--teal);text-decoration:none}a:hover{text-decoration:underline}
a:focus-visible,button:focus-visible,summary:focus-visible,input:focus-visible{outline:2px solid var(--amber);outline-offset:2px}
.wrap{max-width:1080px;margin:0 auto;padding:0 24px}

/* masthead */
.mast{background:var(--teal-deep);color:#e9efe9;padding:56px 0 40px}
.mast .eyebrow{font-size:12px;letter-spacing:.3em;text-transform:uppercase;color:#8fc0b5;font-weight:700}
.mast h1{font-family:var(--serif);font-weight:600;font-size:clamp(2.4rem,1.4rem+4vw,4.4rem);line-height:1.02;margin:14px 0 12px;text-wrap:balance;color:#f4f7f2}
.mast .sub{max-width:62ch;font-size:1.06rem;color:#b9c9c2}
.mast .meta{display:flex;gap:26px;flex-wrap:wrap;margin-top:22px;font-size:13px;color:#8fa39b}
.mast .meta b{color:#e9efe9;font-family:var(--mono);font-weight:600}
/* horizon ruler */
.ruler{margin-top:38px}
.ruler .lab{font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:#8fc0b5;margin-bottom:10px}
.r-track{position:relative;height:3px;background:linear-gradient(90deg,#2e7d32,#b7791f 45%,#37568c 90%);border-radius:2px}
.r-stops{display:flex;justify-content:space-between;margin-top:10px;font-size:12.5px;color:#b9c9c2;gap:8px;flex-wrap:wrap}
.r-stops span b{display:block;color:#f4f7f2;font-family:var(--mono);font-size:13px}
.r-x{color:#7d8a84;text-decoration:line-through}

/* thesis */
.thesis{border-left:4px solid var(--teal);background:#fff;margin:36px 0;padding:20px 24px;font-family:var(--serif);font-size:1.12rem}
.thesis b{color:var(--teal-ink)}

/* stack */
h2{font-family:var(--serif);font-weight:600;font-size:1.65rem;margin:44px 0 6px;text-wrap:balance}
.h-sub{color:var(--muted);margin:0 0 18px;max-width:70ch}
.stack{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}
.card{all:unset;cursor:pointer;display:flex;flex-direction:column;gap:8px;background:#fff;border:1px solid var(--rule);border-top:3px solid var(--pc);padding:16px 18px;border-radius:3px}
.card:hover{border-color:var(--pc)}
.card.meta{background:transparent;border-style:dashed;border-top-style:solid}
.c-head{display:flex;justify-content:space-between;align-items:baseline;gap:10px}
.c-title{font-family:var(--serif);font-size:1.08rem;font-weight:600}
.c-n{font-family:var(--mono);font-size:13px;color:#fff;background:var(--pc);border-radius:12px;padding:1px 9px}
.c-blurb{font-size:13.5px;color:var(--muted);line-height:1.45}

/* catalog */
.toolbar{position:sticky;top:0;z-index:5;background:var(--paper);padding:14px 0 10px;border-bottom:1px solid var(--rule);margin-top:8px}
.search{width:100%;padding:10px 14px;font:inherit;border:1px solid var(--rule);border-radius:3px;background:#fff;color:var(--ink)}
.fchips{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}
.fchip{all:unset;cursor:pointer;font-size:12.5px;padding:4px 12px;border:1px solid var(--rule);border-radius:16px;background:#fff;color:var(--ink)}
.fchip b{font-family:var(--mono);font-weight:600;color:var(--muted)}
.fchip.active{background:var(--ink);color:#f4f7f2;border-color:var(--ink)}
.fchip.active b{color:#cdd8d2}
.countline{font-size:12.5px;color:var(--muted);margin:10px 0 4px;font-family:var(--mono)}

/* rows */
.rows{margin-bottom:30px}
.row{border-bottom:1px solid var(--rule)}
.row summary{list-style:none;display:grid;grid-template-columns:minmax(180px,2.2fr) 110px 70px minmax(110px,1fr);gap:14px;align-items:center;padding:11px 6px;cursor:pointer}
.row summary::-webkit-details-marker{display:none}
.row summary:hover{background:#fff}
.row[open]{background:#fff;border-left:3px solid var(--teal);padding-left:3px}
.r-name{font-weight:600}
.pill{justify-self:start;font-size:11px;font-weight:600;color:#fff;background:var(--pc);border-radius:12px;padding:2px 9px;white-space:nowrap}
.r-hz{font-family:var(--mono);font-size:13px;white-space:nowrap}
.r-country{font-size:13px;color:var(--muted)}
.r-body{padding:2px 16px 16px;max-width:75ch}
.r-signal{margin:6px 0;font-size:14px}
.r-quote{margin:10px 0;padding:10px 16px;border-left:3px solid var(--amber);background:var(--paper);font-family:var(--serif);font-size:14.5px}
.r-meta{margin:8px 0 0}
.chip{display:inline-block;font-size:11px;border:1px solid var(--rule);border-radius:3px;padding:1px 7px;color:var(--muted);margin-right:6px}
.chip-warn{border-color:var(--amber);color:var(--amber)}
.chip-flag{border-color:#9b2226;color:#9b2226}
.r-actions{margin:10px 0 0;font-size:13.5px}
.r-act{font-weight:600}

/* masthead nav */
.mnav{display:flex;gap:20px;margin-top:26px;font-size:13px;letter-spacing:.06em;text-transform:uppercase}
.mnav a{color:#8fc0b5;font-weight:600}
.mnav a:hover{color:#f4f7f2;text-decoration:none}

/* charts */
.charts{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px;margin-bottom:16px}
.fig{background:#fff;border:1px solid var(--rule);border-radius:3px;padding:18px 20px 14px;margin:0}
.fig figcaption{font-size:13px;color:var(--muted);margin-bottom:14px;line-height:1.4}
.fig figcaption b{display:block;color:var(--ink);font-family:var(--serif);font-size:16.5px;font-weight:600;margin-bottom:2px}
.fig svg text{user-select:none}
.legendchips{display:flex;flex-wrap:wrap;gap:5px 14px;margin:0 0 14px}
.lg{display:inline-flex;align-items:center;gap:6px;font-size:11.5px;color:var(--muted)}
.lg i{width:10px;height:10px;border-radius:2px;background:var(--pc)}

/* world map */
.fig-map{grid-column:1/-1}
.worldmap{width:100%;height:auto;display:block;background:#fbfcfa;border-radius:3px}
.worldmap .mc0{pointer-events:none}
.worldmap .mc{cursor:pointer;transition:fill .12s ease,stroke .12s ease}
.worldmap .mc:hover,.worldmap .mc:focus-visible{stroke:var(--teal-deep);stroke-width:1.1;outline:none}
.worldmap .mc.sel{stroke:var(--amber);stroke-width:1.4}
.maplegend{display:flex;flex-wrap:wrap;gap:6px 14px;margin:12px 0 2px;align-items:center}
.mlg{display:inline-flex;align-items:center;gap:6px;font-size:11.5px;color:var(--muted)}
.mlg i{width:14px;height:11px;border-radius:2px;display:inline-block}
.mapnote{font-size:12.5px;color:var(--muted);margin:8px 0 0}
.mapnote button{all:unset;cursor:pointer;color:var(--teal);font-weight:600;text-decoration:underline}
.mapnote button:focus-visible{outline:2px solid var(--amber);outline-offset:2px}
.map-off{display:inline-block;font-size:12px;font-family:var(--mono);color:var(--muted);border:1px dashed var(--rule);border-radius:12px;padding:2px 10px;margin-left:4px}

/* feedback */
.feedback{background:var(--teal-deep);color:#dfe9e2;border-radius:4px;padding:30px 30px 26px;margin:46px 0}
.feedback h2{color:#f4f7f2;margin:0 0 8px}
.feedback p{max-width:66ch;color:#b9c9c2;margin:6px 0}
.fb-btn{display:inline-block;background:#e9efe9;color:var(--teal-deep);font-weight:700;padding:10px 20px;border-radius:3px;margin:12px 12px 0 0}
.fb-btn:hover{text-decoration:none;background:#fff}
.fb-note{font-size:12.5px;color:#8fa39b;margin-top:14px}
.fb-forms{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:8px}
@media(max-width:680px){.fb-forms{grid-template-columns:1fr}}
.fb-form{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.16);border-radius:4px;padding:16px}
.fb-form h3{color:#f4f7f2;margin:0 0 10px;font-family:var(--serif);font-size:1.08rem}
.fb-form input,.fb-form textarea{width:100%;margin:0 0 9px;padding:9px 11px;font:inherit;font-size:14px;border:1px solid rgba(255,255,255,.22);border-radius:3px;background:#0e2f31;color:#eaf2ee}
.fb-form input::placeholder,.fb-form textarea::placeholder{color:#8fa39b}
.fb-form button{background:#e9efe9;color:var(--teal-deep);font-weight:700;border:none;border-radius:3px;padding:9px 18px;cursor:pointer}
.fb-form button:hover{background:#fff}
.hp{position:absolute!important;left:-9999px;width:1px;height:1px;overflow:hidden}

footer{padding:10px 0 60px;font-size:12.5px;color:var(--muted)}
footer b{color:var(--ink)}

@media(max-width:680px){
  .row summary{grid-template-columns:1fr auto;grid-template-rows:auto auto;row-gap:4px}
  .r-hz{grid-column:2;grid-row:2;justify-self:end}
  .r-country{grid-column:1;grid-row:2}
  .mast{padding:40px 0 30px}
}
@media(prefers-reduced-motion:no-preference){
  .row,.card,.fchip{transition:background .15s ease,border-color .15s ease}
}
"""

JS = """
(function(){
  var state = {cls:'*', q:'', country:''};
  var rows = Array.prototype.slice.call(document.querySelectorAll('.row'));
  var countEl = document.getElementById('count');
  var mapClear = document.getElementById('mapclear');
  var maps = Array.prototype.slice.call(document.querySelectorAll('.worldmap .mc'));
  function scrollToCatalog(){
    document.getElementById('catalog').scrollIntoView({behavior:
      matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth'});
  }
  function apply(){
    var q = state.q.toLowerCase(), n = 0;
    rows.forEach(function(r){
      var ok = (state.cls === '*' || r.dataset.cls === state.cls) &&
               (!state.country || r.dataset.country === state.country) &&
               (!q || r.dataset.search.indexOf(q) !== -1);
      r.style.display = ok ? '' : 'none';
      if (ok) n++;
    });
    countEl.textContent = 'Showing ' + n + ' of ' + rows.length + ' entities' +
      (state.cls !== '*' ? ' \\u00B7 ' + state.cls : '') +
      (state.country ? ' \\u00B7 ' + state.country : '') +
      (q ? ' \\u00B7 \\u201C' + state.q + '\\u201D' : '');
  }
  rows.forEach(function(r){ r.dataset.cls = r.getAttribute('data-class'); });
  document.querySelectorAll('.fchip').forEach(function(ch){
    ch.addEventListener('click', function(){
      document.querySelectorAll('.fchip').forEach(function(c){ c.classList.remove('active'); });
      ch.classList.add('active');
      state.cls = ch.getAttribute('data-filter');
      apply();
    });
  });
  document.querySelectorAll('.card').forEach(function(c){
    c.addEventListener('click', function(){
      var k = c.getAttribute('data-filter');
      var chip = document.querySelector('.fchip[data-filter="' + k + '"]');
      if (chip) chip.click();
      scrollToCatalog();
    });
  });
  function setCountry(name){
    state.country = (state.country === name) ? '' : name;
    maps.forEach(function(m){ m.classList.toggle('sel', m.getAttribute('data-country') === state.country); });
    if (mapClear) mapClear.hidden = !state.country;
    apply();
    if (state.country) scrollToCatalog();
  }
  maps.forEach(function(m){
    m.addEventListener('click', function(){ setCountry(m.getAttribute('data-country')); });
    m.addEventListener('keydown', function(e){
      if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setCountry(m.getAttribute('data-country')); }
    });
  });
  if (mapClear) mapClear.addEventListener('click', function(){ if (state.country) setCountry(state.country); });
  document.getElementById('q').addEventListener('input', function(e){
    state.q = e.target.value.trim(); apply();
  });
  // deep-link: /#class=SMV (from the founder questionnaire) preselects a class filter
  function applyHash(){
    var m = /class=([^&]+)/.exec(location.hash || '');
    if (!m) return;
    var k = decodeURIComponent(m[1]);
    var chip = document.querySelector('.fchip[data-filter="' + k + '"]');
    if (chip){ chip.click(); document.getElementById('catalog').scrollIntoView(); }
  }
  window.addEventListener('hashchange', applyHash);
  apply();
  applyHash();
})();
function atlasPrefill(a){var e=a.getAttribute('data-entity')||'';var f=document.getElementById('fb-entity');var m=document.getElementById('fb-message');if(f)f.value=e;if(m&&!m.value)m.value='Correction for '+e+': ';}
"""

top_countries = ', '.join('%s (%d)' % (c, n) for c, n in countries.most_common(3))

page = []
page.append('<title>Post-Unicorn Finance — The Atlas</title>')
page.append('<style>%s</style>' % CSS)
page.append('<header class="mast"><div class="wrap">')
page.append('<div class="eyebrow">Capital Innovation Atlas</div>')
page.append('<h1>Post-Unicorn Finance</h1>')
page.append('<p class="sub">A source-backed atlas of the funds deploying capital <em>outside</em> the ten-year unicorn playbook — every entry verified against the firm’s own words, sorted by how (and how fast) capital comes back.</p>')
page.append('<div class="meta"><span><b>%d</b> entities</span><span><b>%d</b> countries</span><span><b>%d</b> with stated horizons</span><span>audited <b>%s</b></span></div>'
            % (len(rows), len(countries), horizoned, DATE))
page.append('<div class="ruler"><div class="lab">Liquidity horizon — time until capital returns</div><div class="r-track"></div>'
            '<div class="r-stops"><span><b>&lt;6y</b>Nimble</span><span><b>7–9y</b>SMV, sub-unicorn</span>'
            '<span class="r-x"><b>7–10y</b>unicorn-or-bust</span><span><b>∞</b>Permanent, no exit</span></div></div>')
page.append('<nav class="mnav"><a href="#data">The data</a><a href="#stack">The stack</a><a href="#catalog">The catalog</a><a href="should-you-pursue-venture/">Should you pursue venture?</a><a href="#feedback">Add to it</a></nav>')
page.append('</div></header>')
page.append('<main class="wrap">')
page.append('<div class="thesis">Capital innovation is not a category in this atlas — it is the <b>whole atlas</b>. Every class below is a live experiment in funding companies without betting on power-law unicorns.</div>')
page.append('<h2 id="data">The data picture</h2><p class="h-sub">The atlas at a glance — what kind of funds exist, when their capital comes back, and where in the world they operate. Hover any bar for exact counts.</p>')
page.append('<div class="charts">'
            '<figure class="fig"><figcaption><b>Funds by class</b>%d verified entities across %d classes</figcaption>%s</figure>'
            '<figure class="fig"><figcaption><b>Liquidity horizons</b>When each fund expects capital back, from its own stated terms</figcaption>%s</figure>'
            '</div>' % (len(rows), sum(1 for k in CLASS_ORDER if counts.get(k)), chart_classes(), chart_horizons()))
page.append('<figure class="fig fig-map"><figcaption><b>Where in the world</b>%d funds across %d countries — deeper shade means more funds based there. Click any shaded country to filter the catalog; click it again to clear.</figcaption>'
            '%s<div class="maplegend">%s</div>'
            '<p class="mapnote">Funds with no fixed home base or an unverified location are held off the map, never given a fake one: '
            '<span class="map-off">%d unmapped</span>. <button type="button" id="mapclear" hidden>Clear country filter ✕</button></p>'
            '</figure>' % (len(rows) - world_unknown_n, world_country_n, world_svg, world_legend, world_unknown_n))
page.append('<figure class="fig"><figcaption><b>Where the funds are</b>%d funds across %d countries, colored by asset class</figcaption>'
            '<div class="legendchips">%s</div>%s</figure>'
            % (len(rows), n_country_bars - (1 if any((r.get('country') or 'Unknown') == 'Unknown' for r in rows) else 0),
               legend_chips, country_chart_svg))
page.append('<h2 id="stack">The Post-Unicorn Stack</h2><p class="h-sub">Eight sets: five active experiments, a watch list, a review queue, and one contrast baseline. Select any class to filter the catalog.</p>')
page.append('<div class="stack">%s</div>' % cards_html)
page.append('<h2 id="catalog">The catalog</h2><p class="h-sub">Every entity carries a verbatim quote from its own live pages — expand a row for the evidence. Top countries: %s.</p>' % esc(top_countries))
page.append('<div class="toolbar"><input id="q" class="search" type="search" placeholder="Search by name, country, or how a firm describes itself…" aria-label="Search entities">'
            '<div class="fchips">%s</div><div id="count" class="countline"></div></div>' % chips_html)
page.append('<div class="rows">%s</div>' % rows_html)
page.append(
    '<section class="feedback" id="feedback"><h2>Add to the atlas</h2>'
    '<p>The list is read-only by design — every entry must survive a source-check against the firm’s own site before it earns a row. But the hunt is open to everyone: what you send is a lead we verify, never a direct edit.</p>'
    '<div class="fb-forms">'
    '<form name="suggest-a-fund" method="POST" data-netlify="true" netlify-honeypot="bot-field" class="fb-form" id="suggest">'
    '<input type="hidden" name="form-name" value="suggest-a-fund">'
    '<p class="hp"><label>Leave this empty <input name="bot-field"></label></p>'
    '<h3>Suggest a fund</h3>'
    '<input name="fund_name" placeholder="Fund name" required>'
    '<input name="website" type="url" placeholder="Website (https://…)">'
    '<textarea name="why" rows="3" placeholder="Why it belongs — ideally the firm’s own words, with a link"></textarea>'
    '<input name="horizon" placeholder="Stated exit horizon, if any (e.g. 3–5y)">'
    '<input name="your_email" type="email" placeholder="Your email (optional)">'
    '<button type="submit">Send suggestion</button>'
    '</form>'
    '<form name="atlas-feedback" method="POST" data-netlify="true" netlify-honeypot="bot-field" class="fb-form">'
    '<input type="hidden" name="form-name" value="atlas-feedback">'
    '<input type="hidden" name="entity" id="fb-entity" value="">'
    '<p class="hp"><label>Leave this empty <input name="bot-field"></label></p>'
    '<h3>Feedback or a correction</h3>'
    '<textarea name="message" id="fb-message" rows="5" placeholder="Your feedback, or a correction to a specific firm (please include a source link)" required></textarea>'
    '<input name="your_email" type="email" placeholder="Your email (optional)">'
    '<button type="submit">Send feedback</button>'
    '</form>'
    '</div>'
    '<p class="fb-note">These forms activate once the page is live on Netlify — submissions land in your Netlify “Forms” dashboard, not in the atlas. Nothing here edits the list directly; every lead is source-checked first.</p>'
    '</section>')
page.append('<footer><p><b>Method.</b> Classes follow the thesis-owner’s input→output model (market size in, liquidity speed out). Admission requires a live page, an allocator test, and non-unicorn vocabulary in the firm’s own words; unverifiable claims are flagged, never invented. Full audit trail lives in the Post-Unicorn-Finance repository (<b>data/evidence/atlas.csv</b>, audited %s).</p></footer>' % DATE)
page.append('</main>')
page.append('<script>%s</script>' % JS)

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(page))
print('WROTE', OUT, os.path.getsize(OUT), 'bytes ·', len(rows), 'entities ·', len(countries), 'countries')

# Also emit the deployable standalone index.html (title + style -> <head>, rest -> <body>).
head = '\n'.join(page[:2])           # page[0]=<title>, page[1]=<style>
body = '\n'.join(page[2:])           # header + main + script
standalone = (
    '<!doctype html>\n<html lang="en">\n<head>\n'
    '<meta charset="utf-8">\n'
    '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
    '<meta name="description" content="A source-backed atlas of capital allocators operating outside classic unicorn venture capital.">\n'
    + head + '\n</head>\n<body>\n' + body + '\n</body>\n</html>\n')
os.makedirs(os.path.dirname(WRAP_OUT), exist_ok=True)
with open(WRAP_OUT, 'w', encoding='utf-8') as f:
    f.write(standalone)
print('WROTE', WRAP_OUT, os.path.getsize(WRAP_OUT), 'bytes (deployable)')
